### ISSUE TITLE
E-Mail Mapping is not working.

### ISSUE THREAD

**Issue by tomofu74** [humhub/enterprise-issues#11]
Administration login -> Administration menu -> user administration -> groups (tab) -> (select a group and do setting on right-side dropdown menu (gear icon) -> Manage group: xxx, then click "E-Mail Mapping" tab.
![humhub2020-08-14 11 20 57](https://user-images.githubusercontent.com/19162094/90210049-f7c20580-de27-11ea-936a-1398f0a0a8fe.png)

It goes Internal server error. Log is bellow:
Error: Call to a member function validateCsrfToken() on string in /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Controller.php:203 Stack trace: #0 /var/www/html/humhub/protected/humhub/components/Controller.php(191): yii\web\Controller->beforeAction() #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): humhub\components\Controller->beforeAction() #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction() #3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction() #4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest() #5 /var/www/html/humhub/index.php(25): yii\base\Application->run() #6 {main}

Humhub : ver.1.6.2
with Enterprise Edition

**Comment by luke-** [comment]
Fixed in E-Mail Whitelist Module 1.0.1
