### ISSUE TITLE
Space Menu Issues with Custom Themes

### ISSUE THREAD

**Issue by Felli** [humhub/enterprise-issues#2]
Refer to here for more information. https://github.com/sashatravkina/humhub-themes-flathub-v2/issues/1

**Comment by buddh4** [comment]
Please explain some more details of the relation to the enterprise module/theme, also note that the enterprise theme is part of the enterprise module and not open source.

**Comment by Felli** [comment]
The issue is within the enterprise module itself, if you use a custom theme like how the Flathub is setup, you'll see an issue with the Space menu as seen in the screenshot from the attached issue from above.

### Steps to reproduce
- Enable the enterprise module
- Download and use the FlatHub theme
- Go to the dashboard and look at the Space menu
