### ISSUE TITLE
Unmatched </li> end tag in spaceChooser.php

### ISSUE THREAD

**Issue by shadyrachid** [humhub/enterprise-issues#6]
Internet explorer reports an unmatched </Li> closing tag. I have tracked it to line 80 in enterprise/spacetype/widgets/views/spaceChooser.php

Not a show stopper, but i thought it is worth pointing out.

**Comment by buddh4** [comment]
Hmm, can you provide me with the line number? Can't find it in the latest branch, which module version are you using, this may have been fixed already.

**Comment by buddh4** [comment]
Oh, sorry Line 80 ;), nontheless can you tell me which module version you are running?

**Comment by shadyrachid** [comment]
Version: 1.3.16

**Comment by buddh4** [comment]
Thanks, will be fixed in upcoming release.
